[package]
authors = ["Carbon <carbon1024@foxmail.com>"]
edition = "2021"
name    = "feopack-core"
version = "0.1.0"

[dependencies]
napi             = "3.0.0"
napi-derive      = "3.0.0"
swc_common       = "18.0.1"
swc_ecma_ast     = "19.0.0"
swc_ecma_codegen = "21.0.0"
swc_ecma_parser  = "30.0.0"
swc_ecma_visit   = "19.0.0"
tokio            = { version = "1", features = ["fs"] }
