[package]
authors = ["Carbon <carbon1024@foxmail.com>"]
edition = "2021"
name    = "node-binding"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
feopack-binding = { path = "../feopack-binding" }
feopack-core    = { path = "../feopack-core" }
napi            = { version = "3.0.0", features = ["tokio_rt"] }
napi-derive     = "3.0.0"

[build-dependencies]
napi-build = "2"
