/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ModuleConfig {
  rules: Array<ModuleRule>
}

export interface ModuleRule {
  test: string
  useLoaders: Array<string>
}

export interface Output {
  path: string
  filename: string
}

/** 直接映射前端的打包配置文件  */
export interface RawOptions {
  entry: string
  mode: string
  context: string
  output: Output
  module?: ModuleConfig
  rustPlugins?: Array<string>
}
export declare class Rspack {
  constructor(options: RawOptions, jsRunner?: (ctx: JsLoaderContextInput) => Promise<JsLoaderResultOutput>)
  build(): Promise<void>
}

export interface JsLoaderContextInput {
  loaderState: string
  loaders: Array<string>
  resource: string
  source: string
  projectRoot: string
  skipReadResource: boolean
}

export interface JsLoaderResultOutput {
  source: string
  shortCircuit: boolean
  pitchedLoaderIndex?: number
}
