/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Output {
  path: string
  filename: string
}

/** 直接映射前端的打包配置文件  */
export interface RawOptions {
  entry: string
  mode: string
  context: string
  output: Output
}
export declare class Rspack {
  constructor(options: RawOptions)
  build(): Promise<void>
}
